<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>BetterFishingRodsVisualPrototype</AssemblyName>
    <RootNamespace>BetterFishingRodsVisualResearch</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin/VisualPrototype/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="VisualPrototype.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.BaseLib" Version="5.4.21" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.4.21" PrivateAssets="all" />
    <PackageReference Include="HarmonyX" Version="2.9.0" PrivateAssets="all" />
    <PackageReference Include="Unity3D.SDK" Version="2020.3.13.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
